config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  # Marketing pages
  root to: 'pages#home'
  get 'pricing' => 'pages#pricing'
  get 'access' => 'pages#access'
  get 'contact' => 'pages#contact'
  post :subscribe, controller: :subscriptions, action: :subscribe
  post :access_request, controller: :accesses, action: :access_request


  # Interface
  # resources :flats, only: [:index, :show]
  # resources :wishes, only: [:create, :destroy]
  # get 'wishlist' => 'wishes#index'
  # get 'profile' => 'devise'

  # Admin interface
  mount ForestLiana::Engine => '/forest'

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/pages/about.html.erb
<% content_for(:title_tag) do %>
  Prosper - A propos
<% end %>

<section class="section about">
  <div class="container">
    <div class="row">
      <div class="banner-section text-center hidden-xs">
        <h1>La big data à votre service </h1>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-push-sm-6 landing-section-content">
        <h1>
          Un robot <strong>intelligent</strong> pas seulement
        </h1>
        <p>PROSPER a été inventé par une équipe experimentée qui souhaite apporter un nouveau souffle dans le monde des marchands de biens. </p>
      </div>
      <div class="col-xs-12 col-sm-6 col-pull-sm-6 landing-section-media">
        <div id="landing-team-media" style="background-image: url(<%= image_url "landing-team.png" %>)">
          <%= image_tag "landing-team-content.png" %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/access.html.erb
<% content_for(:title_tag) do %>
  Prosper - Demande d'accès
<% end %>

<div class="section access-section">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <div class="access-section-form text-center">
          <%= form_tag access_request_path, class: "access-form" do %>
            <div class="access-form-title">
              <h1>Demander un accès</h1>
            </div>
            <div class="access-form-inputs">
              <%= text_field_tag 'first_name', nil, placeholder: "Prénom" %>
              <%= text_field_tag 'last_name', nil, placeholder: "Nom" %>
              <%= text_field_tag 'email', nil, placeholder: "Email" %>
              <%= button_tag "Demander un accès", id: "submit" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<section class="banner" style="background-image: url('<%= image_url("banner-image.png") %>');">
  <div class="banner-section text-center">
    <h1>
      Automatiser la prospection immobilière
    </h1>
    <h3>Toutes les annonces immobilières <strong>en temps réel</strong></H3>
    <div class="row">
      <div class="col-xs-12 col-sm-8 col-sm-offset-2">
        <%= link_to "Créer son alerte", access_path, class: "btn" %>
      </div>
    </div>
  </div>
</section>

<section class="landing-section landing-real-estate">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 landing-section-content">
        <div>
          <h1>
            Gagnez du temps en <strong>automatisant</strong> votre recherche
          </h1>
          <p>PROSPER vous permet de suivre toutes les annonces immobilières avec une seule alerte.</p>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 landing-section-media">
        <div id="landing-real-estate-media" style="background-image: url(<%= image_url "landing-real-estate.png" %>)">
          <%= image_tag "landing-real-estate-content.png", class: 'hidden' %>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="landing-section landing-studio">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-pull-sm-6 landing-section-content">
        <h1>
          PROSPER sélectionne pour vous <strong>les meilleures</strong> annonces
        </h1>
        <p>PROSPER croise toutes les données et vous permet d'identifier les plus belles opportunités d'investissement en fcontion de multiples criètres (prix au m², travaux).</p>
      </div>
      <div class="col-xs-12 col-sm-6 col-push-sm-6 landing-section-media">
        <div id="landing-studio-media" style="background-image: url(<%= image_url "landing-studio.png" %>)">
          <%= image_tag "landing-studio-content.png", class: 'hidden' %>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="landing-section landing-team">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 landing-section-content">
        <h1>
          Un robot <strong>intelligent</strong>
        </h1>
        <p>PROSPER est le premier robot qui vous permet de prospecter à votre place, grace à son intelligence artificielle.</p>
      </div>
      <div class="col-xs-12 col-sm-6 landing-section-media">
        <div id="landing-team-media" style="background-image: url(<%= image_url "landing-team.png" %>)">
          <%= image_tag "landing-team-content.png", class: 'hidden' %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/pricing.html.erb
<% content_for(:title_tag) do %>
  Prosper - A propos
<% end %>

<section class="section about">
  <div class="container">
    <div class="row">
      <div class="banner-section text-center hidden-xs">
        <h1>La big data à votre service </h1>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-push-sm-6 landing-section-content">
        <h1>
          Un robot <strong>intelligent</strong> pas seulement
        </h1>
        <p>PROSPER a été inventé par une équipe experimentée qui souhaite apporter un nouveau souffle dans le monde des marchands de biens. </p>
      </div>
      <div class="col-xs-12 col-sm-6 col-pull-sm-6 landing-section-media">
        <div id="landing-team-media" style="background-image: url(<%= image_url "landing-team.png" %>)">
          <%= image_tag "landing-team-content.png" %>
        </div>
      </div>
    </div>
  </div>
</section>